"""Constants for AAP client."""

# Environment variables
AAP_HOST = "AAP_HOST"
AAP_USERNAME = "AAP_USERNAME"
AAP_PASSWORD = "AAP_PASSWORD"
AAP_TOKEN = "AAP_TOKEN"
AAP_TIMEOUT = "AAP_TIMEOUT"

# Default values
DEFAULT_TIMEOUT = 30
DEFAULT_PAGE_SIZE = 20

# API endpoints
API_VERSION_ENDPOINT = "/api/"
CONTROLLER_API_VERSION_ENDPOINT = "/api/controller/v2/"
GATEWAY_API_VERSION_ENDPOINT = "/api/gateway/v1/"

# HTTP response codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_ACCEPTED = 202
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_METHOD_NOT_ALLOWED = 405
HTTP_CONFLICT = 409
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504
